srtrelay:
  image: ghcr.io/voc/srtrelay/srtrelay:latest
  restart: always
  container_name: srtrelay
  volumes:
    - ./srtrelay-config.toml:/home/srtrelay/config.toml
  ports:
    - "2222:2222/udp"
    - "8080:8080/tcp"